---
title: "API to Excel/CSV Example"
author: "Dykema, Bill"
date: "2021/10/01"
output:
  html_document: default
---

## Notes for exporting to HTML file:
#### Set working directory: setwd("[Working Folder]")
#### install.packages("rmarkdown")
#### Knit to HTML for easy viewing: rmarkdown::render("api-excel.Rmd", "all")

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# API to Excel/CSV example

## Load R libraries
```{r libraries}

# GET request packages for reading from the API
#install.packages("httr")
library(httr)

# JSON converter
#install.packages("jsonlite")
library(jsonlite)

# Data analysis packages
#install.packages("tidyverse")
library(tidyverse)

# Excel packages
#install.packages("xlsx")
library(xlsx)
#install.packages("openxlsx")
library(openxlsx)

```

## API Connect and Pull Data
```{r read_api}

# API URL build
drought_area <- "USStatistics"
drought_type <- "GetDroughtSeverityStatisticsByArea"
drought_aoi <- "us"
drought_start <- "8/10/2021"
drought_end <- "8/20/2021"
drought_stat <- "1"
drought_url <- sprintf("https://usdmdataservices.unl.edu/api/%s/%s?aoi=%s&startdate=%s&enddate=%s&statisticsType=%s", drought_area, drought_type, drought_aoi, drought_start, drought_end, drought_stat)
# Send API request
drought_data <- GET(drought_url)
# Check URL status (200 is good)
drought_data
# Convert to DataFrame
df_drought <- fromJSON(content(drought_data, "text"), flatten=TRUE)
# View new DataFrame
df_drought

```

## API Columns
```{r api_columns}

# Display DataFrame columns
summary(df_drought)
str(df_drought)

```

# Format Fields
```{r api_columns_setup}

# Copy DataFrame
df_drought_transformed <- df_drought

# Character to Date/Time
df_drought_transformed[['MapDate']] <- parse_date(df_drought[['MapDate']], '%Y%m%d')
df_drought_transformed[['ValidStart']] <- parse_date(df_drought[['ValidStart']], '%Y-%m-%d')
df_drought_transformed[['ValidEnd']] <- parse_date(df_drought[['ValidEnd']], '%Y-%m-%d')
# Remove commas in field values
df_drought_transformed[['None']] <- as.numeric(gsub(",","",df_drought[['None']]))
df_drought_transformed[['D0']] <- as.numeric(gsub(",","",df_drought[['D0']]))
df_drought_transformed[['D1']] <- as.numeric(gsub(",","",df_drought[['D1']]))
df_drought_transformed[['D2']] <- as.numeric(gsub(",","",df_drought[['D2']]))
df_drought_transformed[['D3']] <- as.numeric(gsub(",","",df_drought[['D3']]))
df_drought_transformed[['D4']] <- as.numeric(gsub(",","",df_drought[['D4']]))
# View DataFrame
df_drought_transformed

# Display default may appear to cut-off decimals, you can override this
#options(digits=20)
#df_drought_transformed

```

## Transformed Columns
```{r transformed_columns}

# Display DataFrame columns
summary(df_drought_transformed)
str(df_drought_transformed)

```

## Write API to Excel
```{r api_to_excel}

# Send API DataFrame to Excel file
write.xlsx2(df_drought_transformed, file='testtable_api_export.xlsx', row.names=FALSE)

```

## Write API to CSV
```{r api_to_csv}

# Send API DataFrame to CSV file
write.csv(df_drought_transformed, file='testtable_api_export.csv', row.names=FALSE)

```