---
title: "Excel to/from CSV Example"
author: "Dykema, Bill"
date: "2021/09/09"
output:
  html_document: default
---

## Notes for exporting to HTML file:
#### Set working directory: setwd("[Working Folder]")
#### install.packages("rmarkdown")
#### Knit to HTML for easy viewing: rmarkdown::render("excel-csv.Rmd", "all")

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Excel and CSV read and write example

# Load R libraries

```{r libraries}

## Load libraries

# Excel package
# install.packages("xlsx")
library(xlsx)

```

## Read CSV file

```{r read_csv_file}

## Create DataFrame from CSV file
df_csv <- read.csv("testtable_source.csv", stringsAsFactors=FALSE)

## View your new DataFrame
df_csv

```

## Read Excel file

```{r read_excel_file}

## Create DataFrame from Excel file
df_excel <- read.xlsx("testtable_source.xlsx", sheetIndex=1)

## View your new DataFrame
df_excel

```

## CSV Columns

```{r csv_columns}

## Display DataFrame columns
summary(df_csv)

```

## Excel Columns

```{r excel_columns}

## Display DataFrame columns
summary(df_excel)

```

## Write CSV to Excel
```{r csv_to_excel}

## Send CSV DataFrame to Excel file


```